/**
 * This file used handle all the messages
 * @author Didijobs <rgy713>
 */
module.exports = {
	LOGIN_REGISTERED: 'Successfully registered',
	PHONE_OTP_GENERATED: 'mobile otp generated successfully',
	LOGIN_SUCCESS: 'Successfully login',
	LOGIN_REQUIRED: 'User must be login',
	OTP_GENERATED: 'OTP generated successfully',
	OTP_MESSAGE: {
		title: 'OTP Message',
		message:
			'Welcome! your mobile verification code for Didijob App is: ${otp}'
	},
	SERVICE_PROVIDER_COUNT_FETCHED:
		'service provider counts fetched successfully',
	JOB_POSTER_COUNT_FETCHED: 'job poster count fetched successfully',
	MOBILE_OTP_VERIFIED: 'mobile otp verified successfully',
	MOBILE_OTP_VERIFICATION_FAILED: 'invalid otp',
	OTP_VERIFIED: 'email verified successfully',
	OTP_VERIFICATION_FAILED: 'email already verified',
	DRIVER_LICENSE_URL_FRONT: 'driver license url front updated successfully',
	DRIVER_LICENSE_URL_BACK: 'driver license url back updated successfully',
	USER_NOT_EXIST: 'User not exist',
	USER_ALREADY_EXIST: 'User already exist',
	USER_DELETED: 'User deleted successfully',
	LOCATION_UPDATED: 'Location updated successfully',
	INVALID_CREDENTIAL: 'Invalid credentials',
	PASSWORD_NOT_MATCHED: 'Password not matched',
	IMAGE_UPLOAD_SUCCESS: 'Image uploaded successfully',
	FILE_UPLOAD_SUCCESS: 'File uploaded successfully',
	UPLOAD_ERROR: 'File uploaded error',
	NOT_AUTHORIZED: 'Not authorized to access this api',
	CREATE_ERR_ORDER: 'Error in order creation',
	DELETE_SUCCESS: 'Successfully deleted',
	CREATE_SUCCESS: 'Successfully created',
	UPDATE_SUCCESS: 'Successfully Updated',
	FILE_REQUIRED: 'File required to upload',
	SUCCESS: 'SUCCESS',
	VERIFY_EMAIL: 'Verify Email',
	EXISTS: 'This email or phone number already exists.',
	JOB_CREATED: 'Job created successfully',
	JOB_UPDATED: 'Job updated successfully',
	JOB_UPDATED_ERR: 'Error in job update',
	JOB_DELETED: 'Job deleted successfully',
	JOB_FETCHED_ALL: 'ALL Jobs fetched successfully',
	JOB_FETCHED_BY_ID: 'Job fetched by ID successfully',
	JOB_REVIEW_ADDED: 'Job review added successfully',
	JOB_REVIEW_FETCHED: 'Job review fetched successfully',
	USER_REVIEW_ADDED: 'User review added successfully',
	USER_REVIEW_FETCHED: 'User review fetched successfully',
	CHAT_GROUP_ADDED: 'Chat group added successfully',
	CHAT_GROUP_DELETED: 'Chat group deleted successfully',
	CHAT_GROUP_FETCHED: 'Chat group fetched successfully',
	JOB_APPLICATION_ADDED: 'Job application added successfully',
	JOB_APPLICATION_FETCHED: 'Job application fetched successfully',
	JOB_APPLICATION_UPDATED: 'Job application updated successfully',
	JOB_APPLICATION_ACCEPTED: 'Job application accepted ',
	JOB_APPLICATION_CANCELLED: 'Job application cancelled',
	JOB_SKILL_CREATED: 'Job skill created successfully',
	JOB_SKILL_DELETED: 'Job skill updated successfully',
	DEVICE_TOKEN_DELETED: 'Device Token deleted  successfully',
	DEVICE_TOKEN_RESET: 'Device Token reset successfully',
	DEVICE_TOKEN_UPDATED: 'Device Token updated successfully',
	USER_SKILL_FETCHED: 'User skill fetched successfully',
	USER_SKILL_ADDED: 'User skill added successfully',
	USER_SKILL_UPDATED: 'User skill updated successfully',
	COMMON_SKILL_FETCHED: 'Common skill fetched successfully',
	USER_BANK_ADDED: 'User bank added successfully',
	USER_BANK_UPDATED: 'User bank updated successfully',
	USER_BANK_FETCHED: 'User banks fetched successfully',
	USER_BANK_FETCHED_BY_ID: 'User bank fetched successfully',
	USER_BANK_DELETED: 'User bank deleted successfully',
	ACCOUNT_SET_DEFAULT: 'Account set default successfully',
	USER_SKILLS_ADDED: 'User skills added successfully',
	USER_SKILLS_UPDATED: 'User skills updated successfully',
	NOTIFICATION_STATUS_UPDATED: 'Notification status updated successfully',
	USER_PROFILE_FETCHED: 'profile fetched successfully',
	PHONE_UPDATED: 'Phone updated successfully',
	NAME_UPDATED: 'Name updated successfully',
	IMAGE_UPDATED: 'Image updated successfully',
	USER_TYPE_UPDATED: 'User type updated successfully',
	SSN_UPDATED: 'Ssn updated successfully',
	DRIVER_LICENSE_URL: 'Driver license URL and SSN updated successfully',
	FAQ_FETCHED: 'FAQs fetched successfully',
	EMAIL_SEND_ERR: 'Error in sending OTP on email',
	JOB_REPORTED: 'Job report created successfully',
	USER_CONVERSATION_FETCHED: 'User conversation list fetched successfully',
	MESSAGE_HISTORY_FETCHED: 'Message history fetched successfully',
	CHAT_PINNED: 'Chat pinned successfully',
	CHAT_UNPINNED: 'Chat unpinned successfully',
	CHAT_DELETED: 'Chat deleted successfully',
	MANY_CHAT_DELETED: 'many chats deleted successfully',
	JOB_DISPUTE_CREATED: 'Job dispute created successfully',
	VIEW_JOB_DISPUTE: 'Job dispute viewed',
	CHAT_DISPUTE_CANCEL: 'Job Dispute cancelled successfully',
	CREATE_CHAT_REPORT: 'chat report created successfully',
	MESSAGE_READ_MARKED: 'message marked read successfully',
	MESSAGE_SENT: 'message sent successfully',
	BAD_WORDS: 'bad wwords are not allowed',
	MESSAGE_EDITED: 'message edited successfully',
	MESSAGE_DELETED: 'message deleted successfully',
	CHAT_REPORT_CREATED: 'chat report created successfully',
	USER_JOBS_FETCHED: 'your jobs fetched successfully',
	USER_OPEN_JOB_FETCHED: 'open job fetched successfully',
	JOB_CANCELED: 'job cancelled successfully',
	JOB_COMPLETED: 'job completed',
	FEEDBACK_CREATED: 'feedback created successfully',
	ALL_JOB_APPLICATION_FETCHED: 'all job applications fetched successfully',
	EMAIL_UPDATED: 'email updated successfully',
	CARD_ADDED: 'card added successfully',
	CARD_ALREADY_ADDED: 'card already exists',
	CARD_UPDATED: 'card updated successfully',
	CARD_DELETED: 'card deleted successfully',
	CARD_SET_DEFAULT: 'default card selected',
	CARD_FETCHED: 'card fetched successfully',
	DEFAULT_CARD_FETCHED: 'default card fetched successfully',
	PAYMENT_SUCCESSFULL: 'Paymnet completed successfully',
	JOB_MARK_DISPUTED: 'Job marked dispute successfully'
};
